name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup Bun env 🏗
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies 👨🏻‍💻
        run: bun install

      - name: Run linter 👀
        run: bun run lint
